/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the UpdateCartRequestPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCartRequestPayload{}

// UpdateCartRequestPayload struct for UpdateCartRequestPayload
type UpdateCartRequestPayload struct {
	CartStatus *CartCartStatus `json:"cartStatus,omitempty"`
	CustomerData *CartCustomerData `json:"customerData,omitempty"`
	Locale *string `json:"locale,omitempty"`
}

// NewUpdateCartRequestPayload instantiates a new UpdateCartRequestPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCartRequestPayload() *UpdateCartRequestPayload {
	this := UpdateCartRequestPayload{}
	var cartStatus CartCartStatus = CARTCARTSTATUS_UNKNOWN
	this.CartStatus = &cartStatus
	return &this
}

// NewUpdateCartRequestPayloadWithDefaults instantiates a new UpdateCartRequestPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCartRequestPayloadWithDefaults() *UpdateCartRequestPayload {
	this := UpdateCartRequestPayload{}
	var cartStatus CartCartStatus = CARTCARTSTATUS_UNKNOWN
	this.CartStatus = &cartStatus
	return &this
}

// GetCartStatus returns the CartStatus field value if set, zero value otherwise.
func (o *UpdateCartRequestPayload) GetCartStatus() CartCartStatus {
	if o == nil || IsNil(o.CartStatus) {
		var ret CartCartStatus
		return ret
	}
	return *o.CartStatus
}

// GetCartStatusOk returns a tuple with the CartStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCartRequestPayload) GetCartStatusOk() (*CartCartStatus, bool) {
	if o == nil || IsNil(o.CartStatus) {
		return nil, false
	}
	return o.CartStatus, true
}

// IsSetCartStatus returns a boolean if a field has been set.
func (o *UpdateCartRequestPayload) IsSetCartStatus() bool {
	if o != nil && !IsNil(o.CartStatus) {
		return true
	}

	return false
}

// SetCartStatus gets a reference to the given CartCartStatus and assigns it to the CartStatus field.
func (o *UpdateCartRequestPayload) SetCartStatus(v CartCartStatus) {
	o.CartStatus = &v
}

// GetCustomerData returns the CustomerData field value if set, zero value otherwise.
func (o *UpdateCartRequestPayload) GetCustomerData() CartCustomerData {
	if o == nil || IsNil(o.CustomerData) {
		var ret CartCustomerData
		return ret
	}
	return *o.CustomerData
}

// GetCustomerDataOk returns a tuple with the CustomerData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCartRequestPayload) GetCustomerDataOk() (*CartCustomerData, bool) {
	if o == nil || IsNil(o.CustomerData) {
		return nil, false
	}
	return o.CustomerData, true
}

// IsSetCustomerData returns a boolean if a field has been set.
func (o *UpdateCartRequestPayload) IsSetCustomerData() bool {
	if o != nil && !IsNil(o.CustomerData) {
		return true
	}

	return false
}

// SetCustomerData gets a reference to the given CartCustomerData and assigns it to the CustomerData field.
func (o *UpdateCartRequestPayload) SetCustomerData(v CartCustomerData) {
	o.CustomerData = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *UpdateCartRequestPayload) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCartRequestPayload) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// IsSetLocale returns a boolean if a field has been set.
func (o *UpdateCartRequestPayload) IsSetLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *UpdateCartRequestPayload) SetLocale(v string) {
	o.Locale = &v
}

func (o UpdateCartRequestPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCartRequestPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CartStatus) {
		toSerialize["cartStatus"] = o.CartStatus
	}
	if !IsNil(o.CustomerData) {
		toSerialize["customerData"] = o.CustomerData
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	return toSerialize, nil
}

type NullableUpdateCartRequestPayload struct {
	value *UpdateCartRequestPayload
	isSet bool
}

func (v NullableUpdateCartRequestPayload) Get() *UpdateCartRequestPayload {
	return v.value
}

func (v *NullableUpdateCartRequestPayload) Set(val *UpdateCartRequestPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCartRequestPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCartRequestPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCartRequestPayload(val *UpdateCartRequestPayload) *NullableUpdateCartRequestPayload {
	return &NullableUpdateCartRequestPayload{value: val, isSet: true}
}

func (v NullableUpdateCartRequestPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCartRequestPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


