/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartProductConfigurationStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartProductConfigurationStep{}

// CartProductConfigurationStep struct for CartProductConfigurationStep
type CartProductConfigurationStep struct {
	Id *string `json:"id,omitempty"`
	Grn *string `json:"grn,omitempty"`
	Label *CartLocalizedText `json:"label,omitempty"`
	Description *CartLocalizedText `json:"description,omitempty"`
	Options []CartProductConfigurationStepOption `json:"options,omitempty"`
}

// NewCartProductConfigurationStep instantiates a new CartProductConfigurationStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartProductConfigurationStep() *CartProductConfigurationStep {
	this := CartProductConfigurationStep{}
	return &this
}

// NewCartProductConfigurationStepWithDefaults instantiates a new CartProductConfigurationStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartProductConfigurationStepWithDefaults() *CartProductConfigurationStep {
	this := CartProductConfigurationStep{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CartProductConfigurationStep) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartProductConfigurationStep) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *CartProductConfigurationStep) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CartProductConfigurationStep) SetId(v string) {
	o.Id = &v
}

// GetGrn returns the Grn field value if set, zero value otherwise.
func (o *CartProductConfigurationStep) GetGrn() string {
	if o == nil || IsNil(o.Grn) {
		var ret string
		return ret
	}
	return *o.Grn
}

// GetGrnOk returns a tuple with the Grn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartProductConfigurationStep) GetGrnOk() (*string, bool) {
	if o == nil || IsNil(o.Grn) {
		return nil, false
	}
	return o.Grn, true
}

// IsSetGrn returns a boolean if a field has been set.
func (o *CartProductConfigurationStep) IsSetGrn() bool {
	if o != nil && !IsNil(o.Grn) {
		return true
	}

	return false
}

// SetGrn gets a reference to the given string and assigns it to the Grn field.
func (o *CartProductConfigurationStep) SetGrn(v string) {
	o.Grn = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CartProductConfigurationStep) GetLabel() CartLocalizedText {
	if o == nil || IsNil(o.Label) {
		var ret CartLocalizedText
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartProductConfigurationStep) GetLabelOk() (*CartLocalizedText, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// IsSetLabel returns a boolean if a field has been set.
func (o *CartProductConfigurationStep) IsSetLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given CartLocalizedText and assigns it to the Label field.
func (o *CartProductConfigurationStep) SetLabel(v CartLocalizedText) {
	o.Label = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CartProductConfigurationStep) GetDescription() CartLocalizedText {
	if o == nil || IsNil(o.Description) {
		var ret CartLocalizedText
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartProductConfigurationStep) GetDescriptionOk() (*CartLocalizedText, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// IsSetDescription returns a boolean if a field has been set.
func (o *CartProductConfigurationStep) IsSetDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given CartLocalizedText and assigns it to the Description field.
func (o *CartProductConfigurationStep) SetDescription(v CartLocalizedText) {
	o.Description = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *CartProductConfigurationStep) GetOptions() []CartProductConfigurationStepOption {
	if o == nil || IsNil(o.Options) {
		var ret []CartProductConfigurationStepOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartProductConfigurationStep) GetOptionsOk() ([]CartProductConfigurationStepOption, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// IsSetOptions returns a boolean if a field has been set.
func (o *CartProductConfigurationStep) IsSetOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []CartProductConfigurationStepOption and assigns it to the Options field.
func (o *CartProductConfigurationStep) SetOptions(v []CartProductConfigurationStepOption) {
	o.Options = v
}

func (o CartProductConfigurationStep) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartProductConfigurationStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Grn) {
		toSerialize["grn"] = o.Grn
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableCartProductConfigurationStep struct {
	value *CartProductConfigurationStep
	isSet bool
}

func (v NullableCartProductConfigurationStep) Get() *CartProductConfigurationStep {
	return v.value
}

func (v *NullableCartProductConfigurationStep) Set(val *CartProductConfigurationStep) {
	v.value = val
	v.isSet = true
}

func (v NullableCartProductConfigurationStep) IsSet() bool {
	return v.isSet
}

func (v *NullableCartProductConfigurationStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartProductConfigurationStep(val *CartProductConfigurationStep) *NullableCartProductConfigurationStep {
	return &NullableCartProductConfigurationStep{value: val, isSet: true}
}

func (v NullableCartProductConfigurationStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartProductConfigurationStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


