/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartMergeCartsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartMergeCartsRequest{}

// CartMergeCartsRequest struct for CartMergeCartsRequest
type CartMergeCartsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	SourceCartIds []string `json:"sourceCartIds,omitempty"`
	TargetCartId *string `json:"targetCartId,omitempty"`
}

// NewCartMergeCartsRequest instantiates a new CartMergeCartsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartMergeCartsRequest() *CartMergeCartsRequest {
	this := CartMergeCartsRequest{}
	return &this
}

// NewCartMergeCartsRequestWithDefaults instantiates a new CartMergeCartsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartMergeCartsRequestWithDefaults() *CartMergeCartsRequest {
	this := CartMergeCartsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartMergeCartsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartMergeCartsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// IsSetTenantId returns a boolean if a field has been set.
func (o *CartMergeCartsRequest) IsSetTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartMergeCartsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSourceCartIds returns the SourceCartIds field value if set, zero value otherwise.
func (o *CartMergeCartsRequest) GetSourceCartIds() []string {
	if o == nil || IsNil(o.SourceCartIds) {
		var ret []string
		return ret
	}
	return o.SourceCartIds
}

// GetSourceCartIdsOk returns a tuple with the SourceCartIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartMergeCartsRequest) GetSourceCartIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SourceCartIds) {
		return nil, false
	}
	return o.SourceCartIds, true
}

// IsSetSourceCartIds returns a boolean if a field has been set.
func (o *CartMergeCartsRequest) IsSetSourceCartIds() bool {
	if o != nil && !IsNil(o.SourceCartIds) {
		return true
	}

	return false
}

// SetSourceCartIds gets a reference to the given []string and assigns it to the SourceCartIds field.
func (o *CartMergeCartsRequest) SetSourceCartIds(v []string) {
	o.SourceCartIds = v
}

// GetTargetCartId returns the TargetCartId field value if set, zero value otherwise.
func (o *CartMergeCartsRequest) GetTargetCartId() string {
	if o == nil || IsNil(o.TargetCartId) {
		var ret string
		return ret
	}
	return *o.TargetCartId
}

// GetTargetCartIdOk returns a tuple with the TargetCartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartMergeCartsRequest) GetTargetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetCartId) {
		return nil, false
	}
	return o.TargetCartId, true
}

// IsSetTargetCartId returns a boolean if a field has been set.
func (o *CartMergeCartsRequest) IsSetTargetCartId() bool {
	if o != nil && !IsNil(o.TargetCartId) {
		return true
	}

	return false
}

// SetTargetCartId gets a reference to the given string and assigns it to the TargetCartId field.
func (o *CartMergeCartsRequest) SetTargetCartId(v string) {
	o.TargetCartId = &v
}

func (o CartMergeCartsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartMergeCartsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.SourceCartIds) {
		toSerialize["sourceCartIds"] = o.SourceCartIds
	}
	if !IsNil(o.TargetCartId) {
		toSerialize["targetCartId"] = o.TargetCartId
	}
	return toSerialize, nil
}

type NullableCartMergeCartsRequest struct {
	value *CartMergeCartsRequest
	isSet bool
}

func (v NullableCartMergeCartsRequest) Get() *CartMergeCartsRequest {
	return v.value
}

func (v *NullableCartMergeCartsRequest) Set(val *CartMergeCartsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartMergeCartsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartMergeCartsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartMergeCartsRequest(val *CartMergeCartsRequest) *NullableCartMergeCartsRequest {
	return &NullableCartMergeCartsRequest{value: val, isSet: true}
}

func (v NullableCartMergeCartsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartMergeCartsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


