/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartListCartsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartListCartsRequest{}

// CartListCartsRequest struct for CartListCartsRequest
type CartListCartsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	PageSize *int64 `json:"pageSize,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`
	Sorts []ListCartsRequestSort `json:"sorts,omitempty"`
	FilterMask *string `json:"filterMask,omitempty"`
	Filter *ListCartsRequestFilter `json:"filter,omitempty"`
}

// NewCartListCartsRequest instantiates a new CartListCartsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartListCartsRequest() *CartListCartsRequest {
	this := CartListCartsRequest{}
	return &this
}

// NewCartListCartsRequestWithDefaults instantiates a new CartListCartsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartListCartsRequestWithDefaults() *CartListCartsRequest {
	this := CartListCartsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartListCartsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListCartsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CartListCartsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartListCartsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CartListCartsRequest) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize) {
		var ret int64
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListCartsRequest) GetPageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CartListCartsRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int64 and assigns it to the PageSize field.
func (o *CartListCartsRequest) SetPageSize(v int64) {
	o.PageSize = &v
}

// GetPageToken returns the PageToken field value if set, zero value otherwise.
func (o *CartListCartsRequest) GetPageToken() string {
	if o == nil || IsNil(o.PageToken) {
		var ret string
		return ret
	}
	return *o.PageToken
}

// GetPageTokenOk returns a tuple with the PageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListCartsRequest) GetPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PageToken) {
		return nil, false
	}
	return o.PageToken, true
}

// HasPageToken returns a boolean if a field has been set.
func (o *CartListCartsRequest) HasPageToken() bool {
	if o != nil && !IsNil(o.PageToken) {
		return true
	}

	return false
}

// SetPageToken gets a reference to the given string and assigns it to the PageToken field.
func (o *CartListCartsRequest) SetPageToken(v string) {
	o.PageToken = &v
}

// GetSorts returns the Sorts field value if set, zero value otherwise.
func (o *CartListCartsRequest) GetSorts() []ListCartsRequestSort {
	if o == nil || IsNil(o.Sorts) {
		var ret []ListCartsRequestSort
		return ret
	}
	return o.Sorts
}

// GetSortsOk returns a tuple with the Sorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListCartsRequest) GetSortsOk() ([]ListCartsRequestSort, bool) {
	if o == nil || IsNil(o.Sorts) {
		return nil, false
	}
	return o.Sorts, true
}

// HasSorts returns a boolean if a field has been set.
func (o *CartListCartsRequest) HasSorts() bool {
	if o != nil && !IsNil(o.Sorts) {
		return true
	}

	return false
}

// SetSorts gets a reference to the given []ListCartsRequestSort and assigns it to the Sorts field.
func (o *CartListCartsRequest) SetSorts(v []ListCartsRequestSort) {
	o.Sorts = v
}

// GetFilterMask returns the FilterMask field value if set, zero value otherwise.
func (o *CartListCartsRequest) GetFilterMask() string {
	if o == nil || IsNil(o.FilterMask) {
		var ret string
		return ret
	}
	return *o.FilterMask
}

// GetFilterMaskOk returns a tuple with the FilterMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListCartsRequest) GetFilterMaskOk() (*string, bool) {
	if o == nil || IsNil(o.FilterMask) {
		return nil, false
	}
	return o.FilterMask, true
}

// HasFilterMask returns a boolean if a field has been set.
func (o *CartListCartsRequest) HasFilterMask() bool {
	if o != nil && !IsNil(o.FilterMask) {
		return true
	}

	return false
}

// SetFilterMask gets a reference to the given string and assigns it to the FilterMask field.
func (o *CartListCartsRequest) SetFilterMask(v string) {
	o.FilterMask = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *CartListCartsRequest) GetFilter() ListCartsRequestFilter {
	if o == nil || IsNil(o.Filter) {
		var ret ListCartsRequestFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListCartsRequest) GetFilterOk() (*ListCartsRequestFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *CartListCartsRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given ListCartsRequestFilter and assigns it to the Filter field.
func (o *CartListCartsRequest) SetFilter(v ListCartsRequestFilter) {
	o.Filter = &v
}

func (o CartListCartsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartListCartsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.PageToken) {
		toSerialize["pageToken"] = o.PageToken
	}
	if !IsNil(o.Sorts) {
		toSerialize["sorts"] = o.Sorts
	}
	if !IsNil(o.FilterMask) {
		toSerialize["filterMask"] = o.FilterMask
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

type NullableCartListCartsRequest struct {
	value *CartListCartsRequest
	isSet bool
}

func (v NullableCartListCartsRequest) Get() *CartListCartsRequest {
	return v.value
}

func (v *NullableCartListCartsRequest) Set(val *CartListCartsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartListCartsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartListCartsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartListCartsRequest(val *CartListCartsRequest) *NullableCartListCartsRequest {
	return &NullableCartListCartsRequest{value: val, isSet: true}
}

func (v NullableCartListCartsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartListCartsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


