/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartSetBillingAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartSetBillingAddressRequest{}

// CartSetBillingAddressRequest struct for CartSetBillingAddressRequest
type CartSetBillingAddressRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	Address *CartPostalAddress `json:"address,omitempty"`
}

// NewCartSetBillingAddressRequest instantiates a new CartSetBillingAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartSetBillingAddressRequest() *CartSetBillingAddressRequest {
	this := CartSetBillingAddressRequest{}
	return &this
}

// NewCartSetBillingAddressRequestWithDefaults instantiates a new CartSetBillingAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartSetBillingAddressRequestWithDefaults() *CartSetBillingAddressRequest {
	this := CartSetBillingAddressRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartSetBillingAddressRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetBillingAddressRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// IsSetTenantId returns a boolean if a field has been set.
func (o *CartSetBillingAddressRequest) IsSetTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartSetBillingAddressRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartSetBillingAddressRequest) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetBillingAddressRequest) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// IsSetCartId returns a boolean if a field has been set.
func (o *CartSetBillingAddressRequest) IsSetCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartSetBillingAddressRequest) SetCartId(v string) {
	o.CartId = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *CartSetBillingAddressRequest) GetAddress() CartPostalAddress {
	if o == nil || IsNil(o.Address) {
		var ret CartPostalAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetBillingAddressRequest) GetAddressOk() (*CartPostalAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// IsSetAddress returns a boolean if a field has been set.
func (o *CartSetBillingAddressRequest) IsSetAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given CartPostalAddress and assigns it to the Address field.
func (o *CartSetBillingAddressRequest) SetAddress(v CartPostalAddress) {
	o.Address = &v
}

func (o CartSetBillingAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartSetBillingAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableCartSetBillingAddressRequest struct {
	value *CartSetBillingAddressRequest
	isSet bool
}

func (v NullableCartSetBillingAddressRequest) Get() *CartSetBillingAddressRequest {
	return v.value
}

func (v *NullableCartSetBillingAddressRequest) Set(val *CartSetBillingAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartSetBillingAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartSetBillingAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartSetBillingAddressRequest(val *CartSetBillingAddressRequest) *NullableCartSetBillingAddressRequest {
	return &NullableCartSetBillingAddressRequest{value: val, isSet: true}
}

func (v NullableCartSetBillingAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartSetBillingAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


