/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartSetShipmentAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartSetShipmentAddressRequest{}

// CartSetShipmentAddressRequest struct for CartSetShipmentAddressRequest
type CartSetShipmentAddressRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	Address *CartPostalAddress `json:"address,omitempty"`
}

// NewCartSetShipmentAddressRequest instantiates a new CartSetShipmentAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartSetShipmentAddressRequest() *CartSetShipmentAddressRequest {
	this := CartSetShipmentAddressRequest{}
	return &this
}

// NewCartSetShipmentAddressRequestWithDefaults instantiates a new CartSetShipmentAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartSetShipmentAddressRequestWithDefaults() *CartSetShipmentAddressRequest {
	this := CartSetShipmentAddressRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartSetShipmentAddressRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetShipmentAddressRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CartSetShipmentAddressRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartSetShipmentAddressRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartSetShipmentAddressRequest) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetShipmentAddressRequest) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// HasCartId returns a boolean if a field has been set.
func (o *CartSetShipmentAddressRequest) HasCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartSetShipmentAddressRequest) SetCartId(v string) {
	o.CartId = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *CartSetShipmentAddressRequest) GetAddress() CartPostalAddress {
	if o == nil || IsNil(o.Address) {
		var ret CartPostalAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetShipmentAddressRequest) GetAddressOk() (*CartPostalAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *CartSetShipmentAddressRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given CartPostalAddress and assigns it to the Address field.
func (o *CartSetShipmentAddressRequest) SetAddress(v CartPostalAddress) {
	o.Address = &v
}

func (o CartSetShipmentAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartSetShipmentAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableCartSetShipmentAddressRequest struct {
	value *CartSetShipmentAddressRequest
	isSet bool
}

func (v NullableCartSetShipmentAddressRequest) Get() *CartSetShipmentAddressRequest {
	return v.value
}

func (v *NullableCartSetShipmentAddressRequest) Set(val *CartSetShipmentAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartSetShipmentAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartSetShipmentAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartSetShipmentAddressRequest(val *CartSetShipmentAddressRequest) *NullableCartSetShipmentAddressRequest {
	return &NullableCartSetShipmentAddressRequest{value: val, isSet: true}
}

func (v NullableCartSetShipmentAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartSetShipmentAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


