/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartCustomerData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartCustomerData{}

// CartCustomerData struct for CartCustomerData
type CartCustomerData struct {
	CustomerGrn *string `json:"customerGrn,omitempty"`
	Firstname *string `json:"firstname,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
	Email *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Groups []string `json:"groups,omitempty"`
	TaxCode *string `json:"taxCode,omitempty"`
	CertifiedEmail *string `json:"certifiedEmail,omitempty"`
	SdiCode *string `json:"sdiCode,omitempty"`
	FiscalCode *string `json:"fiscalCode,omitempty"`
	CompanyName *string `json:"companyName,omitempty"`
	AgentGrn *string `json:"agentGrn,omitempty"`
}

// NewCartCustomerData instantiates a new CartCustomerData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartCustomerData() *CartCustomerData {
	this := CartCustomerData{}
	return &this
}

// NewCartCustomerDataWithDefaults instantiates a new CartCustomerData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartCustomerDataWithDefaults() *CartCustomerData {
	this := CartCustomerData{}
	return &this
}

// GetCustomerGrn returns the CustomerGrn field value if set, zero value otherwise.
func (o *CartCustomerData) GetCustomerGrn() string {
	if o == nil || IsNil(o.CustomerGrn) {
		var ret string
		return ret
	}
	return *o.CustomerGrn
}

// GetCustomerGrnOk returns a tuple with the CustomerGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetCustomerGrnOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerGrn) {
		return nil, false
	}
	return o.CustomerGrn, true
}

// IsSetCustomerGrn returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetCustomerGrn() bool {
	if o != nil && !IsNil(o.CustomerGrn) {
		return true
	}

	return false
}

// SetCustomerGrn gets a reference to the given string and assigns it to the CustomerGrn field.
func (o *CartCustomerData) SetCustomerGrn(v string) {
	o.CustomerGrn = &v
}

// GetFirstname returns the Firstname field value if set, zero value otherwise.
func (o *CartCustomerData) GetFirstname() string {
	if o == nil || IsNil(o.Firstname) {
		var ret string
		return ret
	}
	return *o.Firstname
}

// GetFirstnameOk returns a tuple with the Firstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetFirstnameOk() (*string, bool) {
	if o == nil || IsNil(o.Firstname) {
		return nil, false
	}
	return o.Firstname, true
}

// IsSetFirstname returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetFirstname() bool {
	if o != nil && !IsNil(o.Firstname) {
		return true
	}

	return false
}

// SetFirstname gets a reference to the given string and assigns it to the Firstname field.
func (o *CartCustomerData) SetFirstname(v string) {
	o.Firstname = &v
}

// GetLastname returns the Lastname field value if set, zero value otherwise.
func (o *CartCustomerData) GetLastname() string {
	if o == nil || IsNil(o.Lastname) {
		var ret string
		return ret
	}
	return *o.Lastname
}

// GetLastnameOk returns a tuple with the Lastname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetLastnameOk() (*string, bool) {
	if o == nil || IsNil(o.Lastname) {
		return nil, false
	}
	return o.Lastname, true
}

// IsSetLastname returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetLastname() bool {
	if o != nil && !IsNil(o.Lastname) {
		return true
	}

	return false
}

// SetLastname gets a reference to the given string and assigns it to the Lastname field.
func (o *CartCustomerData) SetLastname(v string) {
	o.Lastname = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CartCustomerData) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// IsSetEmail returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CartCustomerData) SetEmail(v string) {
	o.Email = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *CartCustomerData) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// IsSetPhoneNumber returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *CartCustomerData) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *CartCustomerData) GetGroups() []string {
	if o == nil || IsNil(o.Groups) {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// IsSetGroups returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *CartCustomerData) SetGroups(v []string) {
	o.Groups = v
}

// GetTaxCode returns the TaxCode field value if set, zero value otherwise.
func (o *CartCustomerData) GetTaxCode() string {
	if o == nil || IsNil(o.TaxCode) {
		var ret string
		return ret
	}
	return *o.TaxCode
}

// GetTaxCodeOk returns a tuple with the TaxCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetTaxCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TaxCode) {
		return nil, false
	}
	return o.TaxCode, true
}

// IsSetTaxCode returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetTaxCode() bool {
	if o != nil && !IsNil(o.TaxCode) {
		return true
	}

	return false
}

// SetTaxCode gets a reference to the given string and assigns it to the TaxCode field.
func (o *CartCustomerData) SetTaxCode(v string) {
	o.TaxCode = &v
}

// GetCertifiedEmail returns the CertifiedEmail field value if set, zero value otherwise.
func (o *CartCustomerData) GetCertifiedEmail() string {
	if o == nil || IsNil(o.CertifiedEmail) {
		var ret string
		return ret
	}
	return *o.CertifiedEmail
}

// GetCertifiedEmailOk returns a tuple with the CertifiedEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetCertifiedEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CertifiedEmail) {
		return nil, false
	}
	return o.CertifiedEmail, true
}

// IsSetCertifiedEmail returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetCertifiedEmail() bool {
	if o != nil && !IsNil(o.CertifiedEmail) {
		return true
	}

	return false
}

// SetCertifiedEmail gets a reference to the given string and assigns it to the CertifiedEmail field.
func (o *CartCustomerData) SetCertifiedEmail(v string) {
	o.CertifiedEmail = &v
}

// GetSdiCode returns the SdiCode field value if set, zero value otherwise.
func (o *CartCustomerData) GetSdiCode() string {
	if o == nil || IsNil(o.SdiCode) {
		var ret string
		return ret
	}
	return *o.SdiCode
}

// GetSdiCodeOk returns a tuple with the SdiCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetSdiCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SdiCode) {
		return nil, false
	}
	return o.SdiCode, true
}

// IsSetSdiCode returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetSdiCode() bool {
	if o != nil && !IsNil(o.SdiCode) {
		return true
	}

	return false
}

// SetSdiCode gets a reference to the given string and assigns it to the SdiCode field.
func (o *CartCustomerData) SetSdiCode(v string) {
	o.SdiCode = &v
}

// GetFiscalCode returns the FiscalCode field value if set, zero value otherwise.
func (o *CartCustomerData) GetFiscalCode() string {
	if o == nil || IsNil(o.FiscalCode) {
		var ret string
		return ret
	}
	return *o.FiscalCode
}

// GetFiscalCodeOk returns a tuple with the FiscalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetFiscalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.FiscalCode) {
		return nil, false
	}
	return o.FiscalCode, true
}

// IsSetFiscalCode returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetFiscalCode() bool {
	if o != nil && !IsNil(o.FiscalCode) {
		return true
	}

	return false
}

// SetFiscalCode gets a reference to the given string and assigns it to the FiscalCode field.
func (o *CartCustomerData) SetFiscalCode(v string) {
	o.FiscalCode = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *CartCustomerData) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// IsSetCompanyName returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *CartCustomerData) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetAgentGrn returns the AgentGrn field value if set, zero value otherwise.
func (o *CartCustomerData) GetAgentGrn() string {
	if o == nil || IsNil(o.AgentGrn) {
		var ret string
		return ret
	}
	return *o.AgentGrn
}

// GetAgentGrnOk returns a tuple with the AgentGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCustomerData) GetAgentGrnOk() (*string, bool) {
	if o == nil || IsNil(o.AgentGrn) {
		return nil, false
	}
	return o.AgentGrn, true
}

// IsSetAgentGrn returns a boolean if a field has been set.
func (o *CartCustomerData) IsSetAgentGrn() bool {
	if o != nil && !IsNil(o.AgentGrn) {
		return true
	}

	return false
}

// SetAgentGrn gets a reference to the given string and assigns it to the AgentGrn field.
func (o *CartCustomerData) SetAgentGrn(v string) {
	o.AgentGrn = &v
}

func (o CartCustomerData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartCustomerData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerGrn) {
		toSerialize["customerGrn"] = o.CustomerGrn
	}
	if !IsNil(o.Firstname) {
		toSerialize["firstname"] = o.Firstname
	}
	if !IsNil(o.Lastname) {
		toSerialize["lastname"] = o.Lastname
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.TaxCode) {
		toSerialize["taxCode"] = o.TaxCode
	}
	if !IsNil(o.CertifiedEmail) {
		toSerialize["certifiedEmail"] = o.CertifiedEmail
	}
	if !IsNil(o.SdiCode) {
		toSerialize["sdiCode"] = o.SdiCode
	}
	if !IsNil(o.FiscalCode) {
		toSerialize["fiscalCode"] = o.FiscalCode
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.AgentGrn) {
		toSerialize["agentGrn"] = o.AgentGrn
	}
	return toSerialize, nil
}

type NullableCartCustomerData struct {
	value *CartCustomerData
	isSet bool
}

func (v NullableCartCustomerData) Get() *CartCustomerData {
	return v.value
}

func (v *NullableCartCustomerData) Set(val *CartCustomerData) {
	v.value = val
	v.isSet = true
}

func (v NullableCartCustomerData) IsSet() bool {
	return v.isSet
}

func (v *NullableCartCustomerData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartCustomerData(val *CartCustomerData) *NullableCartCustomerData {
	return &NullableCartCustomerData{value: val, isSet: true}
}

func (v NullableCartCustomerData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartCustomerData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


