/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartListPaymentMethodsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartListPaymentMethodsResponse{}

// CartListPaymentMethodsResponse struct for CartListPaymentMethodsResponse
type CartListPaymentMethodsResponse struct {
	Payments []CartPaymentData `json:"payments,omitempty"`
}

// NewCartListPaymentMethodsResponse instantiates a new CartListPaymentMethodsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartListPaymentMethodsResponse() *CartListPaymentMethodsResponse {
	this := CartListPaymentMethodsResponse{}
	return &this
}

// NewCartListPaymentMethodsResponseWithDefaults instantiates a new CartListPaymentMethodsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartListPaymentMethodsResponseWithDefaults() *CartListPaymentMethodsResponse {
	this := CartListPaymentMethodsResponse{}
	return &this
}

// GetPayments returns the Payments field value if set, zero value otherwise.
func (o *CartListPaymentMethodsResponse) GetPayments() []CartPaymentData {
	if o == nil || IsNil(o.Payments) {
		var ret []CartPaymentData
		return ret
	}
	return o.Payments
}

// GetPaymentsOk returns a tuple with the Payments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartListPaymentMethodsResponse) GetPaymentsOk() ([]CartPaymentData, bool) {
	if o == nil || IsNil(o.Payments) {
		return nil, false
	}
	return o.Payments, true
}

// HasPayments returns a boolean if a field has been set.
func (o *CartListPaymentMethodsResponse) HasPayments() bool {
	if o != nil && !IsNil(o.Payments) {
		return true
	}

	return false
}

// SetPayments gets a reference to the given []CartPaymentData and assigns it to the Payments field.
func (o *CartListPaymentMethodsResponse) SetPayments(v []CartPaymentData) {
	o.Payments = v
}

func (o CartListPaymentMethodsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartListPaymentMethodsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payments) {
		toSerialize["payments"] = o.Payments
	}
	return toSerialize, nil
}

type NullableCartListPaymentMethodsResponse struct {
	value *CartListPaymentMethodsResponse
	isSet bool
}

func (v NullableCartListPaymentMethodsResponse) Get() *CartListPaymentMethodsResponse {
	return v.value
}

func (v *NullableCartListPaymentMethodsResponse) Set(val *CartListPaymentMethodsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCartListPaymentMethodsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCartListPaymentMethodsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartListPaymentMethodsResponse(val *CartListPaymentMethodsResponse) *NullableCartListPaymentMethodsResponse {
	return &NullableCartListPaymentMethodsResponse{value: val, isSet: true}
}

func (v NullableCartListPaymentMethodsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartListPaymentMethodsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


