/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartCreateCartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartCreateCartResponse{}

// CartCreateCartResponse struct for CartCreateCartResponse
type CartCreateCartResponse struct {
	Id *string `json:"id,omitempty"`
}

// NewCartCreateCartResponse instantiates a new CartCreateCartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartCreateCartResponse() *CartCreateCartResponse {
	this := CartCreateCartResponse{}
	return &this
}

// NewCartCreateCartResponseWithDefaults instantiates a new CartCreateCartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartCreateCartResponseWithDefaults() *CartCreateCartResponse {
	this := CartCreateCartResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CartCreateCartResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartCreateCartResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *CartCreateCartResponse) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CartCreateCartResponse) SetId(v string) {
	o.Id = &v
}

func (o CartCreateCartResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartCreateCartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCartCreateCartResponse struct {
	value *CartCreateCartResponse
	isSet bool
}

func (v NullableCartCreateCartResponse) Get() *CartCreateCartResponse {
	return v.value
}

func (v *NullableCartCreateCartResponse) Set(val *CartCreateCartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCartCreateCartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCartCreateCartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartCreateCartResponse(val *CartCreateCartResponse) *NullableCartCreateCartResponse {
	return &NullableCartCreateCartResponse{value: val, isSet: true}
}

func (v NullableCartCreateCartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartCreateCartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


