/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartLocalizedText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartLocalizedText{}

// CartLocalizedText struct for CartLocalizedText
type CartLocalizedText struct {
	Value *map[string]string `json:"value,omitempty"`
}

// NewCartLocalizedText instantiates a new CartLocalizedText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartLocalizedText() *CartLocalizedText {
	this := CartLocalizedText{}
	return &this
}

// NewCartLocalizedTextWithDefaults instantiates a new CartLocalizedText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartLocalizedTextWithDefaults() *CartLocalizedText {
	this := CartLocalizedText{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CartLocalizedText) GetValue() map[string]string {
	if o == nil || IsNil(o.Value) {
		var ret map[string]string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartLocalizedText) GetValueOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CartLocalizedText) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]string and assigns it to the Value field.
func (o *CartLocalizedText) SetValue(v map[string]string) {
	o.Value = &v
}

func (o CartLocalizedText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartLocalizedText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableCartLocalizedText struct {
	value *CartLocalizedText
	isSet bool
}

func (v NullableCartLocalizedText) Get() *CartLocalizedText {
	return v.value
}

func (v *NullableCartLocalizedText) Set(val *CartLocalizedText) {
	v.value = val
	v.isSet = true
}

func (v NullableCartLocalizedText) IsSet() bool {
	return v.isSet
}

func (v *NullableCartLocalizedText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartLocalizedText(val *CartLocalizedText) *NullableCartLocalizedText {
	return &NullableCartLocalizedText{value: val, isSet: true}
}

func (v NullableCartLocalizedText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartLocalizedText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


