/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartSetCustomPriceOnItemsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartSetCustomPriceOnItemsRequest{}

// CartSetCustomPriceOnItemsRequest struct for CartSetCustomPriceOnItemsRequest
type CartSetCustomPriceOnItemsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	CartItems []CartSetCustomPriceOnItemsRequestCartItem `json:"cartItems,omitempty"`
}

// NewCartSetCustomPriceOnItemsRequest instantiates a new CartSetCustomPriceOnItemsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartSetCustomPriceOnItemsRequest() *CartSetCustomPriceOnItemsRequest {
	this := CartSetCustomPriceOnItemsRequest{}
	return &this
}

// NewCartSetCustomPriceOnItemsRequestWithDefaults instantiates a new CartSetCustomPriceOnItemsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartSetCustomPriceOnItemsRequestWithDefaults() *CartSetCustomPriceOnItemsRequest {
	this := CartSetCustomPriceOnItemsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartSetCustomPriceOnItemsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetCustomPriceOnItemsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// IsSetTenantId returns a boolean if a field has been set.
func (o *CartSetCustomPriceOnItemsRequest) IsSetTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartSetCustomPriceOnItemsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartSetCustomPriceOnItemsRequest) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetCustomPriceOnItemsRequest) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// IsSetCartId returns a boolean if a field has been set.
func (o *CartSetCustomPriceOnItemsRequest) IsSetCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartSetCustomPriceOnItemsRequest) SetCartId(v string) {
	o.CartId = &v
}

// GetCartItems returns the CartItems field value if set, zero value otherwise.
func (o *CartSetCustomPriceOnItemsRequest) GetCartItems() []CartSetCustomPriceOnItemsRequestCartItem {
	if o == nil || IsNil(o.CartItems) {
		var ret []CartSetCustomPriceOnItemsRequestCartItem
		return ret
	}
	return o.CartItems
}

// GetCartItemsOk returns a tuple with the CartItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetCustomPriceOnItemsRequest) GetCartItemsOk() ([]CartSetCustomPriceOnItemsRequestCartItem, bool) {
	if o == nil || IsNil(o.CartItems) {
		return nil, false
	}
	return o.CartItems, true
}

// IsSetCartItems returns a boolean if a field has been set.
func (o *CartSetCustomPriceOnItemsRequest) IsSetCartItems() bool {
	if o != nil && !IsNil(o.CartItems) {
		return true
	}

	return false
}

// SetCartItems gets a reference to the given []CartSetCustomPriceOnItemsRequestCartItem and assigns it to the CartItems field.
func (o *CartSetCustomPriceOnItemsRequest) SetCartItems(v []CartSetCustomPriceOnItemsRequestCartItem) {
	o.CartItems = v
}

func (o CartSetCustomPriceOnItemsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartSetCustomPriceOnItemsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.CartItems) {
		toSerialize["cartItems"] = o.CartItems
	}
	return toSerialize, nil
}

type NullableCartSetCustomPriceOnItemsRequest struct {
	value *CartSetCustomPriceOnItemsRequest
	isSet bool
}

func (v NullableCartSetCustomPriceOnItemsRequest) Get() *CartSetCustomPriceOnItemsRequest {
	return v.value
}

func (v *NullableCartSetCustomPriceOnItemsRequest) Set(val *CartSetCustomPriceOnItemsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartSetCustomPriceOnItemsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartSetCustomPriceOnItemsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartSetCustomPriceOnItemsRequest(val *CartSetCustomPriceOnItemsRequest) *NullableCartSetCustomPriceOnItemsRequest {
	return &NullableCartSetCustomPriceOnItemsRequest{value: val, isSet: true}
}

func (v NullableCartSetCustomPriceOnItemsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartSetCustomPriceOnItemsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


