/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartApplyCouponsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartApplyCouponsRequest{}

// CartApplyCouponsRequest struct for CartApplyCouponsRequest
type CartApplyCouponsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	CouponCodes []string `json:"couponCodes,omitempty"`
}

// NewCartApplyCouponsRequest instantiates a new CartApplyCouponsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartApplyCouponsRequest() *CartApplyCouponsRequest {
	this := CartApplyCouponsRequest{}
	return &this
}

// NewCartApplyCouponsRequestWithDefaults instantiates a new CartApplyCouponsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartApplyCouponsRequestWithDefaults() *CartApplyCouponsRequest {
	this := CartApplyCouponsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartApplyCouponsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartApplyCouponsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// IsSetTenantId returns a boolean if a field has been set.
func (o *CartApplyCouponsRequest) IsSetTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartApplyCouponsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartApplyCouponsRequest) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartApplyCouponsRequest) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// IsSetCartId returns a boolean if a field has been set.
func (o *CartApplyCouponsRequest) IsSetCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartApplyCouponsRequest) SetCartId(v string) {
	o.CartId = &v
}

// GetCouponCodes returns the CouponCodes field value if set, zero value otherwise.
func (o *CartApplyCouponsRequest) GetCouponCodes() []string {
	if o == nil || IsNil(o.CouponCodes) {
		var ret []string
		return ret
	}
	return o.CouponCodes
}

// GetCouponCodesOk returns a tuple with the CouponCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartApplyCouponsRequest) GetCouponCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.CouponCodes) {
		return nil, false
	}
	return o.CouponCodes, true
}

// IsSetCouponCodes returns a boolean if a field has been set.
func (o *CartApplyCouponsRequest) IsSetCouponCodes() bool {
	if o != nil && !IsNil(o.CouponCodes) {
		return true
	}

	return false
}

// SetCouponCodes gets a reference to the given []string and assigns it to the CouponCodes field.
func (o *CartApplyCouponsRequest) SetCouponCodes(v []string) {
	o.CouponCodes = v
}

func (o CartApplyCouponsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartApplyCouponsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.CouponCodes) {
		toSerialize["couponCodes"] = o.CouponCodes
	}
	return toSerialize, nil
}

type NullableCartApplyCouponsRequest struct {
	value *CartApplyCouponsRequest
	isSet bool
}

func (v NullableCartApplyCouponsRequest) Get() *CartApplyCouponsRequest {
	return v.value
}

func (v *NullableCartApplyCouponsRequest) Set(val *CartApplyCouponsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartApplyCouponsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartApplyCouponsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartApplyCouponsRequest(val *CartApplyCouponsRequest) *NullableCartApplyCouponsRequest {
	return &NullableCartApplyCouponsRequest{value: val, isSet: true}
}

func (v NullableCartApplyCouponsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartApplyCouponsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


