/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartUpdateProductsRequestItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartUpdateProductsRequestItem{}

// CartUpdateProductsRequestItem struct for CartUpdateProductsRequestItem
type CartUpdateProductsRequestItem struct {
	Id *string `json:"id,omitempty"`
	Quantity *int64 `json:"quantity,omitempty"`
	ConfigurationSelections []CartProductConfigurationSelection `json:"configurationSelections,omitempty"`
}

// NewCartUpdateProductsRequestItem instantiates a new CartUpdateProductsRequestItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartUpdateProductsRequestItem() *CartUpdateProductsRequestItem {
	this := CartUpdateProductsRequestItem{}
	return &this
}

// NewCartUpdateProductsRequestItemWithDefaults instantiates a new CartUpdateProductsRequestItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartUpdateProductsRequestItemWithDefaults() *CartUpdateProductsRequestItem {
	this := CartUpdateProductsRequestItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CartUpdateProductsRequestItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartUpdateProductsRequestItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *CartUpdateProductsRequestItem) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CartUpdateProductsRequestItem) SetId(v string) {
	o.Id = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CartUpdateProductsRequestItem) GetQuantity() int64 {
	if o == nil || IsNil(o.Quantity) {
		var ret int64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartUpdateProductsRequestItem) GetQuantityOk() (*int64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// IsSetQuantity returns a boolean if a field has been set.
func (o *CartUpdateProductsRequestItem) IsSetQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int64 and assigns it to the Quantity field.
func (o *CartUpdateProductsRequestItem) SetQuantity(v int64) {
	o.Quantity = &v
}

// GetConfigurationSelections returns the ConfigurationSelections field value if set, zero value otherwise.
func (o *CartUpdateProductsRequestItem) GetConfigurationSelections() []CartProductConfigurationSelection {
	if o == nil || IsNil(o.ConfigurationSelections) {
		var ret []CartProductConfigurationSelection
		return ret
	}
	return o.ConfigurationSelections
}

// GetConfigurationSelectionsOk returns a tuple with the ConfigurationSelections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartUpdateProductsRequestItem) GetConfigurationSelectionsOk() ([]CartProductConfigurationSelection, bool) {
	if o == nil || IsNil(o.ConfigurationSelections) {
		return nil, false
	}
	return o.ConfigurationSelections, true
}

// IsSetConfigurationSelections returns a boolean if a field has been set.
func (o *CartUpdateProductsRequestItem) IsSetConfigurationSelections() bool {
	if o != nil && !IsNil(o.ConfigurationSelections) {
		return true
	}

	return false
}

// SetConfigurationSelections gets a reference to the given []CartProductConfigurationSelection and assigns it to the ConfigurationSelections field.
func (o *CartUpdateProductsRequestItem) SetConfigurationSelections(v []CartProductConfigurationSelection) {
	o.ConfigurationSelections = v
}

func (o CartUpdateProductsRequestItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartUpdateProductsRequestItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.ConfigurationSelections) {
		toSerialize["configurationSelections"] = o.ConfigurationSelections
	}
	return toSerialize, nil
}

type NullableCartUpdateProductsRequestItem struct {
	value *CartUpdateProductsRequestItem
	isSet bool
}

func (v NullableCartUpdateProductsRequestItem) Get() *CartUpdateProductsRequestItem {
	return v.value
}

func (v *NullableCartUpdateProductsRequestItem) Set(val *CartUpdateProductsRequestItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCartUpdateProductsRequestItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCartUpdateProductsRequestItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartUpdateProductsRequestItem(val *CartUpdateProductsRequestItem) *NullableCartUpdateProductsRequestItem {
	return &NullableCartUpdateProductsRequestItem{value: val, isSet: true}
}

func (v NullableCartUpdateProductsRequestItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartUpdateProductsRequestItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


