/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartAddProductsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartAddProductsRequest{}

// CartAddProductsRequest struct for CartAddProductsRequest
type CartAddProductsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	Items []CartAddProductsRequestItem `json:"items,omitempty"`
}

// NewCartAddProductsRequest instantiates a new CartAddProductsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartAddProductsRequest() *CartAddProductsRequest {
	this := CartAddProductsRequest{}
	return &this
}

// NewCartAddProductsRequestWithDefaults instantiates a new CartAddProductsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartAddProductsRequestWithDefaults() *CartAddProductsRequest {
	this := CartAddProductsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartAddProductsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartAddProductsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CartAddProductsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartAddProductsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartAddProductsRequest) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartAddProductsRequest) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// HasCartId returns a boolean if a field has been set.
func (o *CartAddProductsRequest) HasCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartAddProductsRequest) SetCartId(v string) {
	o.CartId = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CartAddProductsRequest) GetItems() []CartAddProductsRequestItem {
	if o == nil || IsNil(o.Items) {
		var ret []CartAddProductsRequestItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartAddProductsRequest) GetItemsOk() ([]CartAddProductsRequestItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CartAddProductsRequest) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CartAddProductsRequestItem and assigns it to the Items field.
func (o *CartAddProductsRequest) SetItems(v []CartAddProductsRequestItem) {
	o.Items = v
}

func (o CartAddProductsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartAddProductsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCartAddProductsRequest struct {
	value *CartAddProductsRequest
	isSet bool
}

func (v NullableCartAddProductsRequest) Get() *CartAddProductsRequest {
	return v.value
}

func (v *NullableCartAddProductsRequest) Set(val *CartAddProductsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartAddProductsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartAddProductsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartAddProductsRequest(val *CartAddProductsRequest) *NullableCartAddProductsRequest {
	return &NullableCartAddProductsRequest{value: val, isSet: true}
}

func (v NullableCartAddProductsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartAddProductsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


