/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartSetPaymentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartSetPaymentsRequest{}

// CartSetPaymentsRequest struct for CartSetPaymentsRequest
type CartSetPaymentsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	Payments []CartPaymentData `json:"payments,omitempty"`
}

// NewCartSetPaymentsRequest instantiates a new CartSetPaymentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartSetPaymentsRequest() *CartSetPaymentsRequest {
	this := CartSetPaymentsRequest{}
	return &this
}

// NewCartSetPaymentsRequestWithDefaults instantiates a new CartSetPaymentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartSetPaymentsRequestWithDefaults() *CartSetPaymentsRequest {
	this := CartSetPaymentsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartSetPaymentsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetPaymentsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CartSetPaymentsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartSetPaymentsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartSetPaymentsRequest) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetPaymentsRequest) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// HasCartId returns a boolean if a field has been set.
func (o *CartSetPaymentsRequest) HasCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartSetPaymentsRequest) SetCartId(v string) {
	o.CartId = &v
}

// GetPayments returns the Payments field value if set, zero value otherwise.
func (o *CartSetPaymentsRequest) GetPayments() []CartPaymentData {
	if o == nil || IsNil(o.Payments) {
		var ret []CartPaymentData
		return ret
	}
	return o.Payments
}

// GetPaymentsOk returns a tuple with the Payments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartSetPaymentsRequest) GetPaymentsOk() ([]CartPaymentData, bool) {
	if o == nil || IsNil(o.Payments) {
		return nil, false
	}
	return o.Payments, true
}

// HasPayments returns a boolean if a field has been set.
func (o *CartSetPaymentsRequest) HasPayments() bool {
	if o != nil && !IsNil(o.Payments) {
		return true
	}

	return false
}

// SetPayments gets a reference to the given []CartPaymentData and assigns it to the Payments field.
func (o *CartSetPaymentsRequest) SetPayments(v []CartPaymentData) {
	o.Payments = v
}

func (o CartSetPaymentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartSetPaymentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.Payments) {
		toSerialize["payments"] = o.Payments
	}
	return toSerialize, nil
}

type NullableCartSetPaymentsRequest struct {
	value *CartSetPaymentsRequest
	isSet bool
}

func (v NullableCartSetPaymentsRequest) Get() *CartSetPaymentsRequest {
	return v.value
}

func (v *NullableCartSetPaymentsRequest) Set(val *CartSetPaymentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCartSetPaymentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCartSetPaymentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartSetPaymentsRequest(val *CartSetPaymentsRequest) *NullableCartSetPaymentsRequest {
	return &NullableCartSetPaymentsRequest{value: val, isSet: true}
}

func (v NullableCartSetPaymentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartSetPaymentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


