/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartAddProductsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartAddProductsResponse{}

// CartAddProductsResponse struct for CartAddProductsResponse
type CartAddProductsResponse struct {
	Items []CartAddProductsResponseItem `json:"items,omitempty"`
}

// NewCartAddProductsResponse instantiates a new CartAddProductsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartAddProductsResponse() *CartAddProductsResponse {
	this := CartAddProductsResponse{}
	return &this
}

// NewCartAddProductsResponseWithDefaults instantiates a new CartAddProductsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartAddProductsResponseWithDefaults() *CartAddProductsResponse {
	this := CartAddProductsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CartAddProductsResponse) GetItems() []CartAddProductsResponseItem {
	if o == nil || IsNil(o.Items) {
		var ret []CartAddProductsResponseItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartAddProductsResponse) GetItemsOk() ([]CartAddProductsResponseItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CartAddProductsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CartAddProductsResponseItem and assigns it to the Items field.
func (o *CartAddProductsResponse) SetItems(v []CartAddProductsResponseItem) {
	o.Items = v
}

func (o CartAddProductsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartAddProductsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCartAddProductsResponse struct {
	value *CartAddProductsResponse
	isSet bool
}

func (v NullableCartAddProductsResponse) Get() *CartAddProductsResponse {
	return v.value
}

func (v *NullableCartAddProductsResponse) Set(val *CartAddProductsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCartAddProductsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCartAddProductsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartAddProductsResponse(val *CartAddProductsResponse) *NullableCartAddProductsResponse {
	return &NullableCartAddProductsResponse{value: val, isSet: true}
}

func (v NullableCartAddProductsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartAddProductsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


