/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the ListCartsRequestFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCartsRequestFilter{}

// ListCartsRequestFilter struct for ListCartsRequestFilter
type ListCartsRequestFilter struct {
	SearchTerms []string `json:"searchTerms,omitempty"`
	CustomerEmails []string `json:"customerEmails,omitempty"`
	CustomerFirstnames []string `json:"customerFirstnames,omitempty"`
	CustomerLastnames []string `json:"customerLastnames,omitempty"`
	CustomerPhones []string `json:"customerPhones,omitempty"`
	CartIds []string `json:"cartIds,omitempty"`
	CartStatus *ListCartsRequestFilterCartStatus `json:"cartStatus,omitempty"`
	CreatedAt []ListCartsRequestFilterDate `json:"createdAt,omitempty"`
	AgentGrn *string `json:"agentGrn,omitempty"`
}

// NewListCartsRequestFilter instantiates a new ListCartsRequestFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCartsRequestFilter() *ListCartsRequestFilter {
	this := ListCartsRequestFilter{}
	var cartStatus ListCartsRequestFilterCartStatus = LISTCARTSREQUESTFILTERCARTSTATUS_UNKNOWN
	this.CartStatus = &cartStatus
	return &this
}

// NewListCartsRequestFilterWithDefaults instantiates a new ListCartsRequestFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCartsRequestFilterWithDefaults() *ListCartsRequestFilter {
	this := ListCartsRequestFilter{}
	var cartStatus ListCartsRequestFilterCartStatus = LISTCARTSREQUESTFILTERCARTSTATUS_UNKNOWN
	this.CartStatus = &cartStatus
	return &this
}

// GetSearchTerms returns the SearchTerms field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetSearchTerms() []string {
	if o == nil || IsNil(o.SearchTerms) {
		var ret []string
		return ret
	}
	return o.SearchTerms
}

// GetSearchTermsOk returns a tuple with the SearchTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetSearchTermsOk() ([]string, bool) {
	if o == nil || IsNil(o.SearchTerms) {
		return nil, false
	}
	return o.SearchTerms, true
}

// IsSetSearchTerms returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetSearchTerms() bool {
	if o != nil && !IsNil(o.SearchTerms) {
		return true
	}

	return false
}

// SetSearchTerms gets a reference to the given []string and assigns it to the SearchTerms field.
func (o *ListCartsRequestFilter) SetSearchTerms(v []string) {
	o.SearchTerms = v
}

// GetCustomerEmails returns the CustomerEmails field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCustomerEmails() []string {
	if o == nil || IsNil(o.CustomerEmails) {
		var ret []string
		return ret
	}
	return o.CustomerEmails
}

// GetCustomerEmailsOk returns a tuple with the CustomerEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCustomerEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomerEmails) {
		return nil, false
	}
	return o.CustomerEmails, true
}

// IsSetCustomerEmails returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCustomerEmails() bool {
	if o != nil && !IsNil(o.CustomerEmails) {
		return true
	}

	return false
}

// SetCustomerEmails gets a reference to the given []string and assigns it to the CustomerEmails field.
func (o *ListCartsRequestFilter) SetCustomerEmails(v []string) {
	o.CustomerEmails = v
}

// GetCustomerFirstnames returns the CustomerFirstnames field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCustomerFirstnames() []string {
	if o == nil || IsNil(o.CustomerFirstnames) {
		var ret []string
		return ret
	}
	return o.CustomerFirstnames
}

// GetCustomerFirstnamesOk returns a tuple with the CustomerFirstnames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCustomerFirstnamesOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomerFirstnames) {
		return nil, false
	}
	return o.CustomerFirstnames, true
}

// IsSetCustomerFirstnames returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCustomerFirstnames() bool {
	if o != nil && !IsNil(o.CustomerFirstnames) {
		return true
	}

	return false
}

// SetCustomerFirstnames gets a reference to the given []string and assigns it to the CustomerFirstnames field.
func (o *ListCartsRequestFilter) SetCustomerFirstnames(v []string) {
	o.CustomerFirstnames = v
}

// GetCustomerLastnames returns the CustomerLastnames field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCustomerLastnames() []string {
	if o == nil || IsNil(o.CustomerLastnames) {
		var ret []string
		return ret
	}
	return o.CustomerLastnames
}

// GetCustomerLastnamesOk returns a tuple with the CustomerLastnames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCustomerLastnamesOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomerLastnames) {
		return nil, false
	}
	return o.CustomerLastnames, true
}

// IsSetCustomerLastnames returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCustomerLastnames() bool {
	if o != nil && !IsNil(o.CustomerLastnames) {
		return true
	}

	return false
}

// SetCustomerLastnames gets a reference to the given []string and assigns it to the CustomerLastnames field.
func (o *ListCartsRequestFilter) SetCustomerLastnames(v []string) {
	o.CustomerLastnames = v
}

// GetCustomerPhones returns the CustomerPhones field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCustomerPhones() []string {
	if o == nil || IsNil(o.CustomerPhones) {
		var ret []string
		return ret
	}
	return o.CustomerPhones
}

// GetCustomerPhonesOk returns a tuple with the CustomerPhones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCustomerPhonesOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomerPhones) {
		return nil, false
	}
	return o.CustomerPhones, true
}

// IsSetCustomerPhones returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCustomerPhones() bool {
	if o != nil && !IsNil(o.CustomerPhones) {
		return true
	}

	return false
}

// SetCustomerPhones gets a reference to the given []string and assigns it to the CustomerPhones field.
func (o *ListCartsRequestFilter) SetCustomerPhones(v []string) {
	o.CustomerPhones = v
}

// GetCartIds returns the CartIds field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCartIds() []string {
	if o == nil || IsNil(o.CartIds) {
		var ret []string
		return ret
	}
	return o.CartIds
}

// GetCartIdsOk returns a tuple with the CartIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCartIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CartIds) {
		return nil, false
	}
	return o.CartIds, true
}

// IsSetCartIds returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCartIds() bool {
	if o != nil && !IsNil(o.CartIds) {
		return true
	}

	return false
}

// SetCartIds gets a reference to the given []string and assigns it to the CartIds field.
func (o *ListCartsRequestFilter) SetCartIds(v []string) {
	o.CartIds = v
}

// GetCartStatus returns the CartStatus field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCartStatus() ListCartsRequestFilterCartStatus {
	if o == nil || IsNil(o.CartStatus) {
		var ret ListCartsRequestFilterCartStatus
		return ret
	}
	return *o.CartStatus
}

// GetCartStatusOk returns a tuple with the CartStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCartStatusOk() (*ListCartsRequestFilterCartStatus, bool) {
	if o == nil || IsNil(o.CartStatus) {
		return nil, false
	}
	return o.CartStatus, true
}

// IsSetCartStatus returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCartStatus() bool {
	if o != nil && !IsNil(o.CartStatus) {
		return true
	}

	return false
}

// SetCartStatus gets a reference to the given ListCartsRequestFilterCartStatus and assigns it to the CartStatus field.
func (o *ListCartsRequestFilter) SetCartStatus(v ListCartsRequestFilterCartStatus) {
	o.CartStatus = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetCreatedAt() []ListCartsRequestFilterDate {
	if o == nil || IsNil(o.CreatedAt) {
		var ret []ListCartsRequestFilterDate
		return ret
	}
	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetCreatedAtOk() ([]ListCartsRequestFilterDate, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// IsSetCreatedAt returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given []ListCartsRequestFilterDate and assigns it to the CreatedAt field.
func (o *ListCartsRequestFilter) SetCreatedAt(v []ListCartsRequestFilterDate) {
	o.CreatedAt = v
}

// GetAgentGrn returns the AgentGrn field value if set, zero value otherwise.
func (o *ListCartsRequestFilter) GetAgentGrn() string {
	if o == nil || IsNil(o.AgentGrn) {
		var ret string
		return ret
	}
	return *o.AgentGrn
}

// GetAgentGrnOk returns a tuple with the AgentGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCartsRequestFilter) GetAgentGrnOk() (*string, bool) {
	if o == nil || IsNil(o.AgentGrn) {
		return nil, false
	}
	return o.AgentGrn, true
}

// IsSetAgentGrn returns a boolean if a field has been set.
func (o *ListCartsRequestFilter) IsSetAgentGrn() bool {
	if o != nil && !IsNil(o.AgentGrn) {
		return true
	}

	return false
}

// SetAgentGrn gets a reference to the given string and assigns it to the AgentGrn field.
func (o *ListCartsRequestFilter) SetAgentGrn(v string) {
	o.AgentGrn = &v
}

func (o ListCartsRequestFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCartsRequestFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SearchTerms) {
		toSerialize["searchTerms"] = o.SearchTerms
	}
	if !IsNil(o.CustomerEmails) {
		toSerialize["customerEmails"] = o.CustomerEmails
	}
	if !IsNil(o.CustomerFirstnames) {
		toSerialize["customerFirstnames"] = o.CustomerFirstnames
	}
	if !IsNil(o.CustomerLastnames) {
		toSerialize["customerLastnames"] = o.CustomerLastnames
	}
	if !IsNil(o.CustomerPhones) {
		toSerialize["customerPhones"] = o.CustomerPhones
	}
	if !IsNil(o.CartIds) {
		toSerialize["cartIds"] = o.CartIds
	}
	if !IsNil(o.CartStatus) {
		toSerialize["cartStatus"] = o.CartStatus
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.AgentGrn) {
		toSerialize["agentGrn"] = o.AgentGrn
	}
	return toSerialize, nil
}

type NullableListCartsRequestFilter struct {
	value *ListCartsRequestFilter
	isSet bool
}

func (v NullableListCartsRequestFilter) Get() *ListCartsRequestFilter {
	return v.value
}

func (v *NullableListCartsRequestFilter) Set(val *ListCartsRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableListCartsRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableListCartsRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCartsRequestFilter(val *ListCartsRequestFilter) *NullableListCartsRequestFilter {
	return &NullableListCartsRequestFilter{value: val, isSet: true}
}

func (v NullableListCartsRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCartsRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


