/*
Cart Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cart

import (
	"encoding/json"
)

// checks if the CartTriggerRealignmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CartTriggerRealignmentResponse{}

// CartTriggerRealignmentResponse struct for CartTriggerRealignmentResponse
type CartTriggerRealignmentResponse struct {
	TenantId *string `json:"tenantId,omitempty"`
	CartId *string `json:"cartId,omitempty"`
	CartUpdated *bool `json:"cartUpdated,omitempty"`
}

// NewCartTriggerRealignmentResponse instantiates a new CartTriggerRealignmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCartTriggerRealignmentResponse() *CartTriggerRealignmentResponse {
	this := CartTriggerRealignmentResponse{}
	return &this
}

// NewCartTriggerRealignmentResponseWithDefaults instantiates a new CartTriggerRealignmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartTriggerRealignmentResponseWithDefaults() *CartTriggerRealignmentResponse {
	this := CartTriggerRealignmentResponse{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CartTriggerRealignmentResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartTriggerRealignmentResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CartTriggerRealignmentResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CartTriggerRealignmentResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCartId returns the CartId field value if set, zero value otherwise.
func (o *CartTriggerRealignmentResponse) GetCartId() string {
	if o == nil || IsNil(o.CartId) {
		var ret string
		return ret
	}
	return *o.CartId
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartTriggerRealignmentResponse) GetCartIdOk() (*string, bool) {
	if o == nil || IsNil(o.CartId) {
		return nil, false
	}
	return o.CartId, true
}

// HasCartId returns a boolean if a field has been set.
func (o *CartTriggerRealignmentResponse) HasCartId() bool {
	if o != nil && !IsNil(o.CartId) {
		return true
	}

	return false
}

// SetCartId gets a reference to the given string and assigns it to the CartId field.
func (o *CartTriggerRealignmentResponse) SetCartId(v string) {
	o.CartId = &v
}

// GetCartUpdated returns the CartUpdated field value if set, zero value otherwise.
func (o *CartTriggerRealignmentResponse) GetCartUpdated() bool {
	if o == nil || IsNil(o.CartUpdated) {
		var ret bool
		return ret
	}
	return *o.CartUpdated
}

// GetCartUpdatedOk returns a tuple with the CartUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CartTriggerRealignmentResponse) GetCartUpdatedOk() (*bool, bool) {
	if o == nil || IsNil(o.CartUpdated) {
		return nil, false
	}
	return o.CartUpdated, true
}

// HasCartUpdated returns a boolean if a field has been set.
func (o *CartTriggerRealignmentResponse) HasCartUpdated() bool {
	if o != nil && !IsNil(o.CartUpdated) {
		return true
	}

	return false
}

// SetCartUpdated gets a reference to the given bool and assigns it to the CartUpdated field.
func (o *CartTriggerRealignmentResponse) SetCartUpdated(v bool) {
	o.CartUpdated = &v
}

func (o CartTriggerRealignmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CartTriggerRealignmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CartId) {
		toSerialize["cartId"] = o.CartId
	}
	if !IsNil(o.CartUpdated) {
		toSerialize["cartUpdated"] = o.CartUpdated
	}
	return toSerialize, nil
}

type NullableCartTriggerRealignmentResponse struct {
	value *CartTriggerRealignmentResponse
	isSet bool
}

func (v NullableCartTriggerRealignmentResponse) Get() *CartTriggerRealignmentResponse {
	return v.value
}

func (v *NullableCartTriggerRealignmentResponse) Set(val *CartTriggerRealignmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCartTriggerRealignmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCartTriggerRealignmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartTriggerRealignmentResponse(val *CartTriggerRealignmentResponse) *NullableCartTriggerRealignmentResponse {
	return &NullableCartTriggerRealignmentResponse{value: val, isSet: true}
}

func (v NullableCartTriggerRealignmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartTriggerRealignmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


